package main

import (
	"regexp"
	"strings"
)

// Month abbreviations
var monthNames = map[int]string{
	1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr",
	5: "May", 6: "Jun", 7: "Jul", 8: "Aug",
	9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec",
}

// Directory structure generated by the script
var captureSubfolders = []string{"Flats", "Lights", "Lights/Rejected", "Logs"}
var processingSubfolders = []string{"PixInsight", "Final"}

// formatTargetName handles catalogs M, NGC, IC and capitalizes properly
func formatTargetName(name string) string {
	catalogs := []string{"M", "NGC", "IC"}
	reSpaces := regexp.MustCompile(`[-_.]+`)
	cleanName := reSpaces.ReplaceAllString(name, " ")

	words := strings.Fields(cleanName)
	var formattedWords []string

	reNumMatch := regexp.MustCompile(`^(` + strings.Join(catalogs, "|") + `)(\d+)$`)

	for _, w := range words {
		wUp := strings.ToUpper(w)

		match := reNumMatch.FindStringSubmatch(wUp)
		if match != nil {
			cat := match[1]
			num := match[2]
			if cat == "M" {
				formattedWords = append(formattedWords, cat+num)
			} else {
				formattedWords = append(formattedWords, cat+"_"+num)
			}
			continue
		}

		isCatalog := false
		for _, cat := range catalogs {
			if wUp == cat {
				isCatalog = true
				break
			}
		}
		if isCatalog || isDigit(wUp) {
			formattedWords = append(formattedWords, wUp)
			continue
		}

		// Capitalize
		if len(w) > 0 {
			formattedWords = append(formattedWords, strings.ToUpper(w[:1])+strings.ToLower(w[1:]))
		}
	}

	return strings.Join(formattedWords, "_")
}

func isDigit(s string) bool {
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

func normalizeName(name string) string {
	re := regexp.MustCompile(`[\W_]+`)
	return strings.ToLower(re.ReplaceAllString(name, ""))
}
